---
title: 'Fiscal Impact Update: S&L TTS'
author: ' Manuel Alcala Kovalski, Tyler Powell, Kadija Yilla'
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
vignette: |
  %\VignetteIndexEntry{Vignette Title} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE,
  fig.align = 'center',
  warnings = FALSE,
  message = FALSE,
  cache = TRUE
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r source}
source('src/packages.R')
library('glue')
```


```{r pull data, warnings = FALSE, message = FALSE, hide = TRUE, include = FALSE}
last_hist_date <- as.Date("2020-09-30")
last_proj_date <- last_hist_date + years(2) + months(7)

previous_month <- month(Sys.Date() - months(1))
previous_year <- year(Sys.Date() - months(1)) 
previous_path <- glue::glue('results/{ previous_month }-{previous_year }')

previous <- read_excel(glue('{previous_path}/fim.xlsx'), na = "NA") %>%
  mutate(date = as_date(date)) %>%
  filter(date >= '2017-12-31' & date <= last_proj_date)  %>%
  select(-contains(c('add', 'override')))

update_month <- month(Sys.Date())
update_year <- year(Sys.Date())
update_path <- glue::glue('results/{ update_month }-{update_year }')
      
# update <- read_excel(glue('{update_path}/fim-{update_month}-{update_year}.xlsx'), na = "NA")
update <- read_excel(glue('{update_path}/fim.xlsx'), na = "NA") %>%
  mutate(date = as_date(date)) %>%
  filter(date >= '2017-12-31' & date <= last_proj_date) %>%
  select(-contains(c('add', 'override')))
```

```{r}
library(arsenal)
compare <- comparedf(previous %>% select(date, contains('state')),
          update %>% select(date, contains('state')))

```

```{r}
summary(compare)
```

