---
title: 'Fiscal Impact Update'
subtitle: 'Changes in contributions relative to previous update'
author: ' Manuel Alcala Kovalski, Tyler Powell, Kadija Yilla'
date: "`r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
output:
  html_document:
    toc: true # table of content true
    toc_float: true
    toc_depth: 2
    number_sections: false 
    theme: united
    highlight: zenburn 
    hig.retina: 3
    self_contained: yes
    css: [style.css]
vignette: |
  %\VignetteIndexEntry{Vignette Title} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE,
  fig.align = 'center',
  warning = FALSE,
  message = FALSE,
  cache = FALSE 
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r source}
source('reports/contribution-figures.R')
```

```{r fiscal_impact}
fiscal_impact
```

# Purchases 

## Total

```{r}
federal
state
```

## Excluding grants

```{r purchases-without-grants}
federal_nom  
state_nom 
```

## Grants

```{r grants}
grants 
consumption_grants 
investment_grants 
```

# Taxes

```{r tts}
taxes
federal_taxes
state_taxes
```

## Non-corporate taxes
```{r noncorp-taxes}
noncorp_taxes
federal_noncorp_taxes
state_noncorp_taxes
```
```{r}
corp_taxes
federal_corp_taxes
state_corp_taxes
```

# Transfers

```{r transfers}
transfers
federal_transfers
state_transfers
```

## Health Outlays

```{r health}
health_outlays
federal_health_outlays
state_health_outlays
```

## Subsidies

```{r subsidies}
subsidies

```

## Unemployment Insurance

```{r unemployment insurance}
ui
federal_ui
state_ui
```

## Rebate Checks

```{r}
rebate_checks
```

## Social Benefits Remainder

The contributions of social benefits excluding subsidies, health outalys, unemployment insurance, and rebate checks is below.

```{r social-benefits}
social_benefits
federal_social_benefits
state_social_benefits
```
