---
title: "FIM Update Summary"
runtime: shiny
output:
  html_document:
    df_print: paged
---
```{r, setup, include = FALSE}
knitr::opts_chunk$set( warning = FALSE, message = FALSE, echo = FALSE)
```

```{r, include = FALSE}
library(tidyverse)
library(stringr)
library(reshape2)
library(rmarkdown)
library(TTR)
library(data.table)
library(DataExplorer)
library(shiny)
library(rsconnect)
```

The purpose of this document is to document changes between the previous FIM update and the most recent one. 
## September FIM

### Levels

#### Table
```{r}
fimPrevious <- read_csv("results/09-2020/fim-projections-2020-09-12.csv") 
fimPrevious <- fimPrevious %>% select(-X1) %>% 
  filter(date > "2019-12-31") %>%
  mutate_if(is.numeric, round, 2)

inputPanel(
  selectInput(
    inputId = "col3",
    label = "Select columns",
    choices = names(fimPrevious)[-1], 
    selected = names(fimPrevious)[2:5],
    multiple = TRUE
  )
)
mydata3 <- reactive({
fimPrevious %>%
    select(date, input$col3)
})


library(DT)
renderDT({
  DT::datatable(mydata3(), class = "cell-border stripe", rownames = F, editable = TRUE, 
                extensions = 'Buttons', 
                options = list(dom = 'Bfrtip',
                               buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
})
```

#### Plots
```{r, echo = FALSE}
inputPanel(
selectInput(inputId = "yaxis3",label = "Y-axis",choices = names(fimPrevious)[-1])
)

renderPlot({
  ggplot(fimPrevious, aes_string("date", input$yaxis3)) + geom_line() 
})
```


## October FIM

### Levels

#### Table

```{r}
fimNew <- read_csv("results/10-2020/fim-projections-2020-10-01.csv") 
fimNew <- fimNew %>% select(-X1) %>%
  filter(date > "2019-12-31") %>% 
  mutate_if(is.numeric, round, 2)

inputPanel(
  selectInput(
    inputId = "col2",
    label = "Select columns",
    choices = names(fimNew)[-1], 
    multiple = TRUE
  )
)
mydata2 <- reactive({
fimNew %>%
    select(date, input$col2)
})


library(DT)
renderDT({
  DT::datatable(mydata2(), class = "cell-border stripe", rownames = F, editable = TRUE, extensions = 'Buttons', options = list(
  dom = 'Bfrtip',
  buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
})


```


#### Plots

```{r, echo = FALSE}
inputPanel(
selectInput(inputId = "yaxis2",label = "Y-axis",choices = names(fimNew)[-1])
)

renderPlot({
  ggplot(fimNew, aes_string("date", input$yaxis2)) + geom_line() 
})
```



## Difference in projections

```{r, include = FALSE}
fimNew <- fimNew %>% mutate(id = "Updated") %>% filter(date > "2019-12-31") %>% mutate_if(is.numeric, round, 2)
fimPrevious <- fimPrevious %>% mutate(id = "Previous") %>% filter(date > "2019-12-31") %>% mutate_if(is.numeric, round, 2)

fimPrevious <- fimPrevious %>% select(-starts_with("add"))
fimNew <- fimNew %>% select(-starts_with("add"))


fimNew <- fimNew %>% select(-starts_with("add"))
fimPrevious <- fimPrevious %>% select(-starts_with("add"))
fim_both <- rbind(fimPrevious, fimNew) %>% group_by(id, date)
fim_diff <- select_if(fimNew, is.numeric) - select_if(fimPrevious, is.numeric)
fim_diff <- fim_diff %>% mutate_if(is.numeric, round, 2) %>% mutate(date = fimNew$date)

```


```{r}
inputPanel(
  selectInput(
    inputId = "rank",
    label = "Select rank",
    choices = c(1:10),
    selected = 5
  )
)

diffRank <- reactive({
  fim_diff %>% select_if(is.numeric) %>%  
  rownames_to_column() %>%
  gather(column, value, -rowname) %>%
  group_by(rowname) %>% 
  mutate(rk = rank(-value)) %>%
  filter(rk <= input$rank) %>% 
  arrange(rk, rowname)
}
)

renderDT({
  DT::datatable(diffRank(), class = "cell-border stripe", rownames = F, editable = TRUE, extensions = 'Buttons', options = list(
  dom = 'Bfrtip',
  buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
})
```

```{r}
inputPanel(
  selectInput(
    inputId = "col4",
    label = "Select columns",
    choices = names(fim_diff)[-1], 
    multiple = TRUE
  )
)
mydata4 <- reactive({
fim_diff %>%
    select(date, input$col4)
})


library(DT)
renderDT({
  DT::datatable(mydata4(), class = "cell-border stripe", escape = TRUE,  rownames = F, editable = TRUE, extensions = 'Buttons', options = list(
  pageLength = 25,
  autoWidth = TRUE,
  dom = 'Bfrtip',
  buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
})


```

```{r both, echo = FALSE}

inputPanel(
selectInput(inputId = "yaxis4",label = "Y-axis",choices = names(fim_both)[-1])
)

renderPlot({
  ggplot(fim_both, aes_string("date", input$yaxis4, group = "id", color = "id")) + geom_line() 
})
```