---
title: "Your Document Title"
author: "Document Author"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, results = 'asis',
                      fig.align = "center")
```

```{r}
loadd(fim)
loadd(updated_fim)

```

```{r}
fim %<>% filter(date > '2019-12-31' & date <= '2022-12-31') %>% mutate(key = 'our_projections') 
updated_fim %<>% filter(date > '2019-12-31' & date <= '2022-12-31') %>% mutate(key = 'budget_projections')
```

```{r}
df <-
  fim %>%
  full_join(updated_fim) %>%
  mutate(date = yearquarter(date)) %>%
    mutate(federal_health_outlays = if_else(key == 'our_projections', 
                                          federal_health_outlays - add_federal_health_outlays,
                                          federal_health_outlays),
           state_health_outlays == if_else(key == 'our_projections', 
                                           state_health_outlays - add_state_health_outlays, state_health_outlays))
```

```{r}
df %>%
  select(date, key, unemployment_insurance) %>%
  pivot_longer(unemployment_insurance) %>%
  ggplot(aes(x = date, y = value, fill = key)) +
  geom_col(position = 'dodge')

compare <- function(column){
  df %>%
    select(date, key, {{column}}) %>%
    pivot_longer({{column}}) %>%
    ggplot(aes(x = date, y = value, fill = key)) +
    geom_col(position = 'dodge') +
    ggthemes::theme_hc()
}

compare(unemployment_insurance)
compare(federal_unemployment_insurance)
compare(state_unemployment_insurance)

compare(federal_health_outlays)
compare(state_health_outlays)

compare(federal_medicaid)
compare(state_medicaid)
compare(medicaid)

compare(medicare)
compare(federal_corporate_taxes)

```

```{r}
df %>%
  mutate(federal_health_outlays = if_else(key == 'historical', 
                                          federal_health_outlays - add_federal_health_outlays,
                                          federal_health_outlays))
```
