---
title: "FIM Update Summary"
runtime: shiny
output:
  html_document:
    df_print: paged
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 6.5, fig.height = 4.5, fig.align = "center")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r, include = FALSE}
library(tidyverse)
library(stringr)
library(reshape2)
library(rmarkdown)
library(TTR)
library(data.table)
library(DataExplorer)
library(shiny)
library(rsconnect)
library(lubridate)
library(here)
library(DT)
library(ggtext)
library(ggthemes)
```

The purpose of this document is to document changes between the previous FIM update and the most recent one. 

```{r hardcoded, echo = FALSE}
# PUT ALL HARDCODED VARIABLES HERE
last_hist_date <- '2020-06-30'
```


```{r dates, echo = FALSE}
currentDate <- Sys.Date()
currentYear <- year(currentDate)
previousYear <- year(currentDate - months(1)) 

currentMonth <- month(currentDate)
previousMonth <- month(currentDate - months(1)) 

```

## Previous FIM Update

```{r load previous, echo=FALSE, message=F, warning=FALSE, results='asis'}
previousMonthYear <- if_else(previousMonth >= 10, 
                             paste0(previousMonth, '-', previousYear),
                             paste0('0', previousMonth, '-', previousYear)
)
previousDate <- "2020-09-12"
previousProjection <- paste0('fim-projections', '-', previousDate, '.csv')

previous <- 
  read_csv(
  here('results',
       previousMonthYear, 
       previousProjection
      )
  ) %>%
  select(-X1) %>%
  filter(date > last_hist_date) %>%
  mutate(
    across(
      .cols = where(is_numeric),
      .fns = ~ round(.x, 2)
    )
  ) %>%
  select(-starts_with('add_'), recession) %>%
  as_tibble()

```

### Table 

The table below shows our FIM projections on `r previousDate`:

```{r table previous}

# Select  inputs
inputPanel(
  selectInput(
    inputId = "previousColumns",
    label = "Select columns",
    choices = previous %>% 
              select(where(is.numeric)) %>%
              names(), 
    multiple = TRUE
  )
)

# Create reactive data
previousReactive <-
  reactive({
    previous %>%
    select(date, input$previousColumns)
  })

## Render dynamic table

renderDT({
  DT::datatable(previousReactive(),
                class = "cell-border stripe",
                rownames = F,
                editable = TRUE,
                extensions = 'Buttons',
                options = list(dom = 'Bfrtip',
                               buttons = c('copy',
                                           'excel',
                                           'pdf')
                               )
                )
})
```


### Plots


It may also be helpful to visualize these projections. 
```{r previous plot, echo = FALSE}
inputPanel(
  selectInput(
    inputId = 'previousVariable',
    label = 'Select variables',
    choices = previous %>% 
              select(where(is.numeric)) %>%
              names(),
    selected = "federal_cont",
    multiple = TRUE
  )
)

# Create reactive data
previousReactiveMelt <-
  reactive({
    previous %>%
      select(date, input$previousVariable) %>%
      melt(id = 'date') 
  })


renderPlot({
  previousReactiveMelt() %>%
    ggplot(aes(x = date,
               y = value,
               color = variable)
           ) +
    geom_line() +
    labs(x = '',
         y = '', 
         title = "<span style = 'font-size:16pt; font-family:Helvetica;'>Previous FIM</span>") +
    scale_color_brewer(name = '', 
                       type = 'div',
                       palette = 'Spectral',
                       direction = 1) +
    theme_hc() +
     theme(
    text = element_text(family = "Times"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16, lineheight = 1.2)
  )
})
```


## Current FIM

<!-- ### Levels -->

### Table

```{r load current}
newDate <- "2020-10-15"
currentMonthYear <- if_else(currentMonth >= 10, 
                             paste0(currentMonth, '-', currentYear),
                             paste0('0', currentMonth, '-', currentYear)
)
currentProjection <- paste0('fim', '-', newDate, '.csv')
current <-
  read_csv(
  here('results',
       currentMonthYear, 
       currentProjection
      )
  ) %>%
  filter(date > last_hist_date) %>%
    select(-starts_with('add_'), recession) %>%
  as_tibble() 
 

```

```{r current table, echo = FALSE}

# Select  inputs
inputPanel(
  selectInput(
    inputId = "currentColumns",
    label = "Select columns",
    choices = current %>% 
              select(where(is.numeric)) %>%
              names(), 
    multiple = TRUE
  )
)

# Create reactive data
currentReactive <-
  reactive({
    current %>%
    select(date, input$currentColumns)
  })

## Render dynamic table

renderDT({
  DT::datatable(currentReactive(),
                class = "cell-border stripe",
                rownames = F,
                editable = TRUE,
                extensions = 'Buttons',
                options = list(dom = 'Bfrtip',
                               buttons = c('copy',
                                           'excel',
                                           'pdf')
                               )
                )
})
```

### Plot
```{r current plot}
inputPanel(
  selectInput(
    inputId = 'currentVariable',
    label = 'Select variables',
    choices = current %>% 
              select(where(is.numeric)) %>%
              names(),
    selected = "federal_cont",
    multiple = TRUE
  )
)

# Create reactive data
currentReactiveMelt <-
  reactive({
    current %>%
      select(date, input$currentVariable) %>%
      melt(id = 'date') 
  })


renderPlot({
  currentReactiveMelt() %>%
    ggplot(aes(x = date,
               y = value,
               color = variable)
           ) +
    geom_line() +
    labs(x = '',
         y = '', 
         title = "<span style = 'font-size:16pt; font-family:Helvetica;'>Current FIM</span>") +
    scale_color_brewer(name = '', 
                       type = 'div',
                       palette = 'Spectral',
                       direction = 1) +
    theme_hc() +
     theme(
    text = element_text(family = "Times"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16, lineheight = 1.2)
  )
})
```

## Comparison 

```{r merge}
both <-
  previous %>%
  mutate(key = 0) %>%
  bind_rows(current %>% mutate(key = 1)) %>%
  melt(id = c('date', 'key'))
```
```{r both plot}
inputPanel(
  selectInput(
    inputId = 'variables',
    label = 'Select variables',
    choices = current %>% 
              select(where(is.numeric)) %>%
              names(),
    selected = "federal_cont",
    multiple = TRUE
  )
)

# Create reactive data
bothReactiveMelt <-
  reactive({
 previous %>%
  mutate(key = 0) %>%
  bind_rows(current %>% mutate(key = 1)) %>%
  select(date, key, input$variables) %>%
  melt(id = c('date', 'key'))
  })


renderPlot({
  bothReactiveMelt() %>%
    ggplot(aes(x = date,
               y = value,
               group = key,
               color = key)
           ) +
    geom_line() +
    labs(x = '',
         y = '', 
         title = "<span style = 'font-size:16pt; font-family:Helvetica;'>Current FIM</span>") +
    theme_hc() +
     theme(
    text = element_text(family = "Times"),
    plot.title.position = "plot",
    plot.title = element_markdown(size = 16, lineheight = 1.2)
  )
})
```


<!-- library(DT) -->
<!-- renderDT({ -->
<!--   DT::datatable(mydata3(), class = "cell-border stripe", rownames = F, editable = TRUE, extensions = 'Buttons', options = list( -->
<!--   dom = 'Bfrtip', -->
<!--   buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) -->
<!-- }) -->


<!-- ``` -->


<!-- #### Plots -->



<!-- ```{r, echo = FALSE} -->
<!-- inputPanel( -->
<!-- selectInput(inputId = "yaxis3",label = "Y-axis",choices = names(fim_09)[-1]) -->
<!-- ) -->

<!-- renderPlot({ -->
<!--   ggplot(fim_09, aes_string("date", input$yaxis3)) + geom_line() -->
<!-- }) -->
<!-- ``` -->

<!-- ### Rates -->

<!-- We can also look at the quarterly growth rate for each variable. -->

<!-- #### Table -->

<!-- ```{r} -->
<!-- # fim_09_rate <- fim_09 %>% select(-date) %>% mutate(./lag(.) - 1) %>% -->


<!--  fim_09_rates <- fim_09 %>% mutate_at(.funs = list(rate = ~./lag(.) - 1), .vars = 2:length(fim_09)) %>% select(date, ends_with("rate")) %>% mutate_if(is.numeric, round, 2) -->
<!-- inputPanel( -->
<!--   selectInput( -->
<!--     inputId = "rate09", -->
<!--     label = "Select columns", -->
<!--     choices = names(fim_09_rates)[-1], -->
<!--     multiple = TRUE -->
<!--   ) -->
<!-- ) -->
<!-- rates_09 <- reactive({ -->
<!-- fim_09_rates %>% -->
<!--     select(date, input$rate09) -->
<!-- }) -->


<!-- library(DT) -->
<!-- renderDT({ -->
<!--   DT::datatable(rates_09(), class = "cell-border stripe", rownames = F, editable = TRUE, extensions = 'Buttons', options = list( -->
<!--   dom = 'Bfrtip', -->
<!--   buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) -->
<!-- }) -->



<!-- ``` -->

<!-- #### Plot -->
<!-- ```{r} -->
<!-- inputPanel( -->
<!-- selectInput(inputId = "rateaxis1",label = "Y-axis",choices = names(fim_09_rates)[-1]) -->
<!-- ) -->

<!-- renderPlot({ -->
<!--   ggplot(fim_09_rates, aes_string("date", input$rateaxis1)) + geom_line() -->
<!-- }) -->
<!-- ``` -->




<!-- ## Difference in projections -->





<!-- ```{r, include = FALSE} -->
<!-- fim_new <- fim_09 %>% mutate(id = "Updated") %>% filter(date > "2019-12-31") %>% mutate_if(is.numeric, round, 2) -->
<!-- fim_old <- fim_08 %>% mutate(id = "Previous") %>% filter(date > "2019-12-31") %>% mutate_if(is.numeric, round, 2) -->

<!-- fim_old <- fim_old %>% select(-starts_with("add")) -->
<!-- fim_new <- fim_new %>% select(-starts_with("add")) -->


<!-- fim_09 <- fim_09 %>% select(-starts_with("add")) -->
<!-- fim_08 <- fim_08 %>% select(-starts_with("add")) -->
<!-- fim_both <- rbind(fim_old, fim_new) %>% group_by(id, date) -->
<!-- fim_diff <- fim_09 - fim_08 -->
<!-- fim_diff <- fim_diff %>% mutate_if(is.numeric, round, 2) %>% mutate(date = fim_09$date) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- inputPanel( -->
<!--   selectInput( -->
<!--     inputId = "col4", -->
<!--     label = "Select columns", -->
<!--     choices = names(fim_diff)[-1], -->
<!--     multiple = TRUE -->
<!--   ) -->
<!-- ) -->
<!-- mydata4 <- reactive({ -->
<!-- fim_diff %>% -->
<!--     select(date, input$col4) -->
<!-- }) -->


<!-- library(DT) -->
<!-- renderDT({ -->
<!--   DT::datatable(mydata4(), class = "cell-border stripe", rownames = F, editable = TRUE, extensions = 'Buttons', options = list( -->
<!--   dom = 'Bfrtip', -->
<!--   buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) -->
<!-- }) -->


<!-- ``` -->


<!-- We can also visualize both FIM's side by side -->


<!-- ```{r both, echo = FALSE} -->
<!-- inputPanel( -->
<!-- selectInput(inputId = "yaxis4",label = "Y-axis",choices = names(fim_both)[-1]) -->
<!-- ) -->

<!-- renderPlot({ -->
<!--   ggplot(fim_both, aes_string("date", input$yaxis4, group = "id", color = "id")) + geom_line() -->
<!-- }) -->
<!-- ``` -->

<!-- ### Rates -->

<!-- Calculations for the percentage difference in levels from the 08/04 projections to 09/04 projections. -->

<!-- #### Table -->

<!-- ```{r} -->
<!--  fim_diff_percent <- (fim_09[,2:length(fim_09)] - fim_08[,2:length(fim_08)]) -->

<!--  fim_diff_percent <- (fim_diff_percent/fim_08[,2:length(fim_08)]) -->
<!--  fim_diff_percent <- bind_cols(fim_09$date, fim_diff_percent) -->

<!-- fim_diff_percent <- fim_diff_percent %>% rename(date = ...1) -->
<!--  fim_diff_percent <- fim_diff_percent  %>% filter(date > "2019-12-31") %>% mutate_if(is.numeric, round, 2) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- inputPanel( -->
<!--   selectInput( -->
<!--     inputId = "col5", -->
<!--     label = "Select columns", -->
<!--     choices = names(fim_diff_percent)[-1], -->
<!--     multiple = TRUE -->
<!--   ) -->
<!-- ) -->
<!-- mydata5 <- reactive({ -->
<!-- fim_diff_percent %>% -->
<!--     select(date, input$col5) -->
<!-- }) -->


<!-- library(DT) -->
<!-- renderDT({ -->
<!--   DT::datatable(mydata5(), class = "cell-border stripe", rownames = F, editable = TRUE, extensions = 'Buttons', options = list( -->
<!--   dom = 'Bfrtip', -->
<!--   buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) -->
<!-- }) -->


<!-- ``` -->


<!-- #### Plots -->


<!-- ```{r percent, echo = FALSE} -->
<!-- inputPanel( -->
<!-- selectInput(inputId = "yaxis5",label = "Y-axis",choices = names(fim_diff_percent)[-1]) -->
<!-- ) -->

<!-- renderPlot({ -->
<!--   ggplot(fim_diff_percent, aes_string("date", input$yaxis5)) + geom_line() +  scale_y_continuous(labels=scales::percent) -->
<!-- }) -->
<!-- ``` -->


