---
title: "FIM Components Treemap"
author: "Manuel Alcalá Kovalski"
date: "10/16/2020"
output:
  html_document: default
  pdf_document: default
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 6.5, fig.height = 4.5, fig.align = "center", warnings = FALSE, message = FALSE, cache  = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
source('src/packages.R')
source('src/functions.R')
```

```{r}
library('treemap')

```

```{r}
# Create data
group <- c("group-1","group-2","group-3")
value <- c(13,5,22)
data <- data.frame(group,value)
 
# treemap
treemap(data,
            index="group",
            vSize="value",
            type="index"
            )

# Load fim

last_hist_date <- as.Date("2020-06-30")
last_proj_date <- last_hist_date + years(2) + months(7)
fim <- readRDS('data/processed/fim.RDS') %>%
  filter(date == last_hist_date) %>%
  as_tibble() 
```

```{r}
f <- fim %>%
  select(federal_cont, state_local_cont, taxes_transfers_cont) %>%
  pivot_longer(c(federal_cont, state_local_cont, taxes_transfers_cont)) %>%
  mutate(value = abs(value))

 

 treemap(f, index = 'name', 
          vSize = 'value', 
          type = 'index')
```

