---
title: "Fiscal Impact Update: Changes in Contributions Relative to Previous Update"
author: " Manuel Alcala Kovalski, Tyler Powell, Kadija Yilla"
date: "`r Sys.Date()`"
output: html_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  echo = FALSE,
  fig.align = 'center',
  warnings = FALSE,
  message = FALSE,
  cache = TRUE
)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r source}
source('src/packages.R')
library('glue')
```


```{r pull data, warnings = FALSE, message = FALSE, hide = TRUE, include = FALSE}
last_hist_date <- as.Date("2020-09-30")
last_proj_date <- last_hist_date + years(2) + months(7)

previous_month <- month(Sys.Date() - months(1))
previous_year <- year(Sys.Date() - months(1)) 
previous_path <- glue::glue('results/{ previous_month }-{previous_year }')

previous <- read_excel(glue('{previous_path}/fim-{previous_month}-{previous_year}.xlsx'), na = "NA") %>%
  mutate(date = as_date(date)) %>%
  filter(date >= '2017-12-31' & date <= last_proj_date)  %>%
  select(-contains(c('add', 'override')))

update_month <- month(Sys.Date())
update_year <- year(Sys.Date())
update_path <- glue::glue('results/{ update_month }-{update_year }')
      
# update <- read_excel(glue('{update_path}/fim-{update_month}-{update_year}.xlsx'), na = "NA")
update <- read_excel(glue('{update_path}/fim.xlsx'), na = "NA") %>%
  mutate(date = as_date(date)) %>%
  filter(date >= '2017-12-31' & date <= last_proj_date) %>%
  select(-contains(c('add', 'override')))
```

## Total Quarterly Fiscal Impact

```{r fim, fig.show='hold'}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, fim_bars, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Quarterly Fiscal Impact') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```


```{r fim-ma, fig.show='hold'}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, fim_bars_ma, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '', 
       y = 'Percentage points',
       title =  'Quarterly Fiscal Impact, Four Quarter Moving Average') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r federal-cont}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, federal_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Federal Purchases') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired', direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 

  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r state-cont}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, state_local_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of S&L Purchases') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

## Purchases and Grants

```{r purchases-federal}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, federal_nom_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Federal Purchases Without Grants') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r purchases-state}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, state_local_nom_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of S&L Purchases') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r cgrants}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, federal_cgrants_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Consumption Grants') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r igrants}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, federal_igrants_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Investment Grants') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

## Taxes and Transfers
```{r tts}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, taxes_transfers_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Taxes and Transfers') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r federal-tts}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, federal_taxes_transfers_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Federal Taxes and Transfers') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```


```{r state-tts}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, state_taxes_transfers_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of S&L Taxes and Transfers') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```


## Subsidies

```{r subsidies}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, subsidies_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Subsidies') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r subsidies_federal}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, federal_subsidies_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Federal Subsidies') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```

```{r subsidies_state}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, state_subsidies_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of S&L Subsidies') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```
```{r social-benefits}
previous %>%
  mutate(key = 'previous') %>%
  bind_rows(update %>% mutate(key = 'update')) %>%
  select(date, social_benefits_cont, key) %>%
  group_by(key) %>%
  pivot_longer(
    where(
      is.numeric
    )
  ) %>%
  ggplot(aes(x = date,
             y = value,
             fill = key)
         ) +
  geom_col(position = 'dodge') +
  labs(x = '',
       y = 'Percentage points',
       title =  'Contribution of Social Benefits') +
    scale_fill_brewer(name = "", labels = c('Previous', 'Updated'), type = 'qual', palette = 'Paired',                      direction = 1) +      geom_vline(xintercept  = last_hist_date, linetype =  'dotted') + 
  theme_hc() +
  theme(plot.title.position = 'plot')
```
